export const BASE_URL = 'https://softkomik.com'
export const IMAGE_BASE_URL = 'https://image.softkomik.com'

export const GENRES = [
  'Action',
  'Adventure',
  'Comedy',
  'Cooking',
  'Drama',
  'Ecchi',
  'Fantasy',
  'Harem',
  'Historical',
  'Horror',
  'Isekai',
  'Josei',
  'magic',
  'Martial Arts',
  'Mecha',
  'Military',
  'Music',
  'Mystery',
  'One Shot',
  'Psychological',
  'Romance',
  'School',
  'School Life',
  'Sci-fi',
  'Seinen',
  'Shoujo',
  'Shoujo Ai',
  'Shounen',
  'Shounen Ai',
  'Slice of Life',
  'Sports',
  'Super Power',
  'Supernatural',
  'Thriller',
  'Tragedy',
  'Webtoon'
].sort()
